apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: techchallenge
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/lanchonete
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    server:
      port: 8080
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics