apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-api
  namespace: techchallenge
  labels:
    app: techchallenge-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallenge-api
  template:
    metadata:
      labels:
        app: techchallenge-api
    spec:
      containers:
        - name: techchallenge-api
          image: rafa36/techchallenge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/tech_challenge
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yml
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: app-config
          configMap:
            name: app-config