apiVersion: v1
kind: Service
metadata:
  name: techchallenge-service
  namespace: techchallenge
spec:
  selector:
    app: techchallenge-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer